cxf:
  path: /rest
kieserver:
  auth:
    password: wbadmin
    username: wbadmin
  dmn:
    enabled: true
  drools:
    enabled: true
  location: http://localhost:8090/rest/server
  rest:
    controllers: http://localhost:8080/kie-server/services/rest/server/containers/instances/com.perf:business-application-kjar:1.0-SNAPSHOT/
  serverId: business-application-service
  serverName: business-application-service
server:
  address: localhost
  port: 80
spring:
  profiles:
    #active: test
  banner:
    location: classpath:banner.txt
  datasource:
    driver-class-name: org.h2.Driver
    password: sa
    url: jdbc:h2:./target/spring-boot-jbpm
    username: sa
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: update
        show_sql: false
