package com.perf.demo.model;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class Application implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Applicant applicant;
	private Property property;
	private Integer downpayment;
	private Integer amortization;
	private Integer mortgageamount;

	public Application() {
	}

	public Applicant getApplicant() {
		return this.applicant;
	}

	public void setApplicant(Applicant applicant) {
		this.applicant = applicant;
	}

	public Property getProperty() {
		return this.property;
	}

	public void setProperty(Property property) {
		this.property = property;
	}

	public Integer getDownpayment() {
		return this.downpayment;
	}

	public void setDownpayment(java.lang.Integer downpayment) {
		this.downpayment = downpayment;
	}

	public java.lang.Integer getAmortization() {
		return this.amortization;
	}

	public void setAmortization(java.lang.Integer amortization) {
		this.amortization = amortization;
	}

	public java.lang.Integer getMortgageamount() {
		return this.mortgageamount;
	}

	public void setMortgageamount(java.lang.Integer mortgageamount) {
		this.mortgageamount = mortgageamount;
	}
}