package com.perf.demo.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Property implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Integer age;
	private String address;
	private String locale;
	private Integer saleprice;

	public Property() {
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getLocale() {
		return this.locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	public Integer getSaleprice() {
		return this.saleprice;
	}

	public void setSaleprice(Integer saleprice) {
		this.saleprice = saleprice;
	}
}